// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Phase.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class StateTransitionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "StateTransitions.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "StateTransitions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "StateTransitions")))
            {
                global::Phase.Tests.Features.StateTransitionsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("execute command without result against a vacant phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CatchException")]
        public virtual void ExecuteCommandWithoutResultAgainstAVacantPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("execute command without result against a vacant phase", new string[] {
                        "CatchException"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("phase is vacant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When("executing a command without result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then("an exception should be thrown with message \"Phase must be occupied before executi" +
                    "ng commands and queries\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("execute query against a vacant phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CatchException")]
        public virtual void ExecuteQueryAgainstAVacantPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("execute query against a vacant phase", new string[] {
                        "CatchException"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("phase is vacant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.When("executing a query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("an exception should be thrown with message \"Phase must be occupied before executi" +
                    "ng commands and queries\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("vacate a vacant phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CatchException")]
        public virtual void VacateAVacantPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("vacate a vacant phase", new string[] {
                        "CatchException"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("phase is vacant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.When("vacate phase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("an exception should be thrown with message \"Phase is already vacant\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("occupy vacant phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        public virtual void OccupyVacantPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("occupy vacant phase", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("phase is vacant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.When("occupy phase with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("phase should be occupied with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("occupy occupied phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CatchException")]
        public virtual void OccupyOccupiedPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("occupy occupied phase", new string[] {
                        "CatchException"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("phase is occupied with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.When("occupy phase with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("an exception should be thrown with message \"Phase is already occupied\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("vacate occupied phase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        public virtual void VacateOccupiedPhase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("vacate occupied phase", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("phase is occupied with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.When("vacate phase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("phase should be vacant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("resuse phase instance for different tenant")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        public virtual void ResusePhaseInstanceForDifferentTenant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("resuse phase instance for different tenant", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("phase is occupied with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "AccountId",
                        "cda49d33-00f6-45f8-99e7-bfc30f08e4a08"});
            table1.AddRow(new string[] {
                        "AccountNumber",
                        "1111"});
            table1.AddRow(new string[] {
                        "AccountName",
                        "Checking"});
#line 39
 testRunner.When("phase executes link account command", ((string)(null)), table1, "When ");
#line 44
 testRunner.And("vacate phase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("occupy phase with tenant id \"0e0c4165-b386-45dc-a278-12bfe46f5921\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "AccountId",
                        "505ed83d-56cf-471b-bc3f-5d862e622628"});
            table2.AddRow(new string[] {
                        "AccountNumber",
                        "2222"});
            table2.AddRow(new string[] {
                        "AccountName",
                        "Savings"});
#line 46
 testRunner.When("phase executes link account command", ((string)(null)), table2, "When ");
#line 51
 testRunner.And("phase executes get accounts query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Number",
                        "Name"});
            table3.AddRow(new string[] {
                        "505ed83d-56cf-471b-bc3f-5d862e622628",
                        "2222",
                        "Savings"});
#line 52
 testRunner.Then("the query should return the following accounts", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("reuse phase instance for different tenant then occupy for first tenant")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StateTransitions")]
        public virtual void ReusePhaseInstanceForDifferentTenantThenOccupyForFirstTenant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("reuse phase instance for different tenant then occupy for first tenant", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("phase is occupied with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "AccountId",
                        "cda49d33-00f6-45f8-99e7-bfc30f08e4a08"});
            table4.AddRow(new string[] {
                        "AccountNumber",
                        "1111"});
            table4.AddRow(new string[] {
                        "AccountName",
                        "Checking"});
#line 58
 testRunner.When("phase executes link account command", ((string)(null)), table4, "When ");
#line 63
 testRunner.And("vacate phase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("occupy phase with tenant id \"0e0c4165-b386-45dc-a278-12bfe46f5921\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "AccountId",
                        "505ed83d-56cf-471b-bc3f-5d862e622628"});
            table5.AddRow(new string[] {
                        "AccountNumber",
                        "2222"});
            table5.AddRow(new string[] {
                        "AccountName",
                        "Savings"});
#line 65
 testRunner.When("phase executes link account command", ((string)(null)), table5, "When ");
#line 70
 testRunner.And("vacate phase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("occupy phase with tenant id \"63921ebb-b2b4-44fd-b441-17e730556ac8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.And("phase executes get accounts query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Number",
                        "Name"});
            table6.AddRow(new string[] {
                        "cda49d33-00f6-45f8-99e7-bfc30f08e4a08",
                        "1111",
                        "Checking"});
#line 73
 testRunner.Then("the query should return the following accounts", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion


